### ISSUE TITLE
Adjustable camera zoom levels

### ISSUE THREAD

**Issue by LarsDittberner** [S2-modders/Settlers-DNG-Patches#2]
Hello!
Thank you very much for your work!
I would like to ask if you could add a configuration option for the zoom levels instead of hard coding them. I play in 32:9 and the maximum zoom level is still too low for my liking. Actually I think there is no reason for any restriction at this point.
I would do it by myself, but I tried with different VS versions and non of them could compile the source code without errors.
Maybe you could tell me your IDE setup if thats easier for you. 
Thanks in advance
LD

**Comment by zocker-160** [comment]
Thanks for your kind words, I am using VS 2019 with the XP runtime to make it possible that retro gamers on old hardware can use this patch too.

When you get compilation errors, please make sure you have pulled all git submodules as well when cloning this repository. Otherwise it should work, I am not using any external dependencies not included in this repo and also no fancy C++ features.

As for the zoom levels, the values currently are selected in a way in order to restore the FOV of 4:3 on common widescreen resolutions, it is not meant to increase it.

That being said, I am willing to add a config option, which allows you to override the zoom level to whatever you like, but you will realize quickly, that you don't gain much, as you will also have to adjust the fog height as well (see second image in readme) and if you don't you will not see much.

**Comment by LarsDittberner** [comment]
I would very much appreciate it if you could implement this. Maybe by adding an option to disable the fog completely or in parallel another cofiguration option for the fog height. I don't need fog. I want sunny weather all the time :) Let me know how I can buy you a coffee.

**Comment by zocker-160** [comment]
Sadly currently I have not found a way to manipulate the fog from the DLL. 

Currently the fog height is changed by updating every single map file since those values are part of the map.

**Comment by LarsDittberner** [comment]
Ah ok. Now I understand. Widescreen patch and fog patch are two different things combined in the installer from KonradAr on ModDB.

I had a look into the map editor where you can zoom out a lot further. I opened up some maps before and after the patch. See attached pics. The fog patch kind of disables fog completly until a very huge height (1536 [whatever the unit is]). I assume maps should behave the same way in game. So it seems like fog shouldn't be an issue. 

![afterPatch](https://github.com/S2-modders/Settlers-DNG-Patches/assets/84972812/d8bd34eb-0aa5-449c-b2d8-73edf98f191a)
![beforePatch](https://github.com/S2-modders/Settlers-DNG-Patches/assets/84972812/032d7b8e-f26b-4c2f-a9be-53a876e8cd34)

**Comment by LarsDittberner** [comment]
Works like a charm! Many thanks for that! The maximum zoom (before the fog is visible) is now just right for my liking. Let me know how I can buy you a coffee, kind internet stranger :)

**Comment by zocker-160** [comment]
Glad to hear! Have fun :)

If you so wish, coffee can be bought on [Ko-Fi/zocker_160](https://ko-fi.com/zocker_160) :smiley:
